"""Utilities for rendering a CodeReview as GitHub-flavored markdown."""

from app.models.review import CodeReview, FindingItem, SuggestedFix, Verdict

_VERDICT_LABEL = {
    Verdict.APPROVE: "APPROVE",
    Verdict.REQUEST_CHANGES: "REQUEST_CHANGES",
    Verdict.COMMENT: "COMMENT",
}

_SEVERITY_LABEL = {
    "critical": "CRITICAL",
    "high": "HIGH",
    "medium": "MEDIUM",
    "low": "LOW",
}


def _severity_badge(severity: str | None) -> str:
    if not severity:
        return ""
    label = _SEVERITY_LABEL.get(severity.lower(), severity.upper())
    return f"[{label}]"


def _render_findings(title: str, items: list[FindingItem]) -> str:
    if not items:
        return f"### {title}\n\n_No issues found._\n"

    lines = [f"### {title}\n"]
    for item in items:
        badge = _severity_badge(item.severity)
        location = f"`{item.file}`" if item.file else ""
        if item.line:
            location += f" line {item.line}"
        location_text = f" - {location}" if location else ""
        prefix = f"{badge} " if badge else ""
        lines.append(f"- {prefix}{item.description}{location_text}")
        if item.evidence:
            lines.append(f"  - Evidence: `{item.evidence}`")
    return "\n".join(lines) + "\n"


def _render_fixes(fixes: list[SuggestedFix]) -> str:
    if not fixes:
        return "### Suggested Fixes\n\n_No fixes suggested._\n"

    parts = ["### Suggested Fixes\n"]
    for fix in fixes:
        loc = f"`{fix.file}`" if fix.file else ""
        parts.append(f"#### {fix.issue}" + (f" - {loc}" if loc else ""))
        parts.append(f"\n**Explanation:** {fix.explanation}\n")
        if fix.original:
            parts.append(f"**Before:**\n```\n{fix.original}\n```\n")
        parts.append(f"**After:**\n```\n{fix.improved}\n```\n")
    return "\n".join(parts)


def review_to_markdown(review: CodeReview) -> str:
    """Convert a CodeReview into a clean GitHub PR comment."""

    verdict = _VERDICT_LABEL.get(review.final_verdict, review.final_verdict.value)
    header = (
        f"## AI Code Review - {review.pr_title}\n\n"
        f"> **Verdict:** **{verdict}**\n\n"
        f"{review.summary}\n\n"
        f"---\n\n"
        f"### Scores\n\n"
        f"| Dimension | Score |\n"
        f"|-----------|-------|\n"
        f"| Code Quality | {review.scores.quality}/10 |\n"
        f"| Security | {review.scores.security}/10 |\n"
        f"| Performance | {review.scores.performance}/10 |\n\n"
        f"---\n\n"
    )

    body = "\n".join(
        [
            _render_findings("Bugs", review.bugs),
            _render_findings("Security", review.security),
            _render_findings("Performance", review.performance),
            _render_findings("Code Quality", review.code_quality),
            _render_fixes(review.suggested_fixes),
        ]
    )

    footer = (
        "\n---\n"
        f"_Review generated by AI Code Review Agent. "
        f"Provider: `{review.llm_provider}`. "
        f"PR: [#{review.pr_number}]({review.pr_url})_\n"
    )

    return header + body + footer
