"""Utilities for rendering a CodeReview as GitHub-flavoured markdown."""

from app.models.review import CodeReview, FindingItem, SuggestedFix, Verdict

_VERDICT_EMOJI = {
    Verdict.APPROVE: "✅",
    Verdict.REQUEST_CHANGES: "🚨",
    Verdict.COMMENT: "💬",
}

_SEVERITY_EMOJI = {
    "critical": "🔴",
    "high": "🟠",
    "medium": "🟡",
    "low": "🟢",
}


def _severity_badge(severity: str | None) -> str:
    if not severity:
        return ""
    return _SEVERITY_EMOJI.get(severity.lower(), "") + f" `{severity}`"


def _render_findings(title: str, items: list[FindingItem]) -> str:
    if not items:
        return f"### {title}\n\n_No issues found._\n"

    lines = [f"### {title}\n"]
    for item in items:
        badge = _severity_badge(item.severity)
        location = f"`{item.file}`" if item.file else ""
        if item.line:
            location += f" line {item.line}"
        lines.append(
            f"- {badge} {item.description}" + (f" — {location}" if location else "")
        )
    return "\n".join(lines) + "\n"


def _render_fixes(fixes: list[SuggestedFix]) -> str:
    if not fixes:
        return "### Suggested Fixes\n\n_No fixes suggested._\n"

    parts = ["### Suggested Fixes\n"]
    for fix in fixes:
        loc = f"`{fix.file}`" if fix.file else ""
        parts.append(f"#### {fix.issue}" + (f" — {loc}" if loc else ""))
        parts.append(f"\n**Explanation:** {fix.explanation}\n")
        if fix.original:
            parts.append(f"**Before:**\n```\n{fix.original}\n```\n")
        parts.append(f"**After:**\n```\n{fix.improved}\n```\n")
    return "\n".join(parts)


def review_to_markdown(review: CodeReview) -> str:
    """Convert a :class:`CodeReview` into a clean GitHub PR comment (markdown)."""

    verdict_emoji = _VERDICT_EMOJI.get(review.final_verdict, "💬")
    header = (
        f"## 🤖 AI Code Review — {review.pr_title}\n\n"
        f"> **Verdict:** {verdict_emoji} **{review.final_verdict.value}**\n\n"
        f"{review.summary}\n\n"
        f"---\n\n"
        f"### Scores\n\n"
        f"| Dimension | Score |\n"
        f"|-----------|-------|\n"
        f"| Code Quality | {review.scores.quality}/10 |\n"
        f"| Security | {review.scores.security}/10 |\n"
        f"| Performance | {review.scores.performance}/10 |\n\n"
        f"---\n\n"
    )

    body = "\n".join(
        [
            _render_findings("🐛 Bugs", review.bugs),
            _render_findings("🔐 Security", review.security),
            _render_findings("⚡ Performance", review.performance),
            _render_findings("🧹 Code Quality", review.code_quality),
            _render_fixes(review.suggested_fixes),
        ]
    )

    footer = (
        "\n---\n"
        f"_Review generated by AI Code Review Agent · "
        f"Provider: `{review.llm_provider}` · "
        f"PR: [#{review.pr_number}]({review.pr_url})_\n"
    )

    return header + body + footer
